# NumPy

NumPy, `Numerical Python` anlamaına gelir ve yüksek performanslı sayısal işlemler yapmak için kullanılan bir Python kütüphanesidir. NumPy temel özellikleri arasında çok boyutlu dizileri ve matrisler, matematiksel işlemler, rastgele sayı üretimi ve Fourier dönüşümleri yer almaktadır. Bu özellikler sayesinde Numpy, bilimsel ve mühendislik hesaplamaları için yaygın olarak kullanılan bir kütüphanedir.

NumPy kütüphanesi `np` kısaltma adıyla aşağıdaki gibi eklenir.

In [2]:
import numpy as np

print("Version of NumPy libary: ", np.__version__)

Version of NumPy libary:  2.3.2


Dizi oluşturma:

In [3]:
array = np.array([1, 2, 3, 4, 5, 6])
print("Array: ", array)

Array:  [1 2 3 4 5 6]


Dizinin veri tipini öğrenme: Yukarıdaki dizinin tipi `numpy` veri tiplerinden `ndarray` tipindedir. Python' da olduğu gibi `numpy` kütüphanesinin de kendine özgü veri tipleri vardır. `ndarray` bunlardan biridir.

In [4]:
print("Type of the array: ", type(array))

Type of the array:  <class 'numpy.ndarray'>


Dizi içindeki verilerin tipini öğrenme: Yukarıdaki dizinin içindeki veriler `int64` veri tipindedir.

In [5]:
print("Data type of array elements: ", array.dtype)

Data type of array elements:  int64


NumPy içindeki verilerin tipi en geniş anlamda tanımlanır: Örneğin dizinin içinde hem tam sayı hem de kayar noktalı sayı varsa bu durumda `dtype` değeri kayar noktalı sayı olarak belirlenir. Çünkü kayar noktalı sayı veri türü tam sayıları da kapsar. Kısacası NumPy dizileri, bellek verimliliği ve performans nedeniyle homojen veri tipleri gerektirir, bu nedenle bir dizi için sadece tek bir veri tipi tanımlanır.

In [6]:
array1 = np.array([1, 1.5, 2, 2.5, 3, 3.5, 4])
print("Data type of array elements: ", array1.dtype)

Data type of array elements:  float64


* Soru: Bir NumPy dizisi içinde string veri tipleri nasıl kullanılır?

* Cevap: Bir NumPy dizisi içinde stringler de olabilir. NumPy, dizi elemanları için farklı veri tipleri sağlar ve string veri tipleri de bunlardan biridir. NumPy dizilerinde string veri tipleri, `S` veya `U` karakterleriyle tanımlanır. `S` tipi veri tipleri, `byte` dizileri içindir. `S10` gibi bir veri tipi, her elemanın en fazla `10 byte` uzunluğunda bir `byte` dizisi olduğunu belirtir. Örneğin `hello` kelimesi `S5` tipinde bir dizi elemanıdır. `U` tipi veri tipleri, `Unicode` karakter dizileri içindir. `U10` gibi bir veri tipi, her elemanın en fazla 10 karakter uzunluğunda bir `Unicode` karakter dizisi olduğunu belirtir. Örneğin, `Merhaba` kelimesi `U7` tipinde bir dizi elemanıdır.

NumPy dizilerinde string veri tipleri, çeşitli uygulamalarda kullanılır. Örneğin metin verileri, dosya adları, etiketler ve sınıf adları gibi veriler string veri tipleri kullanılarak depolanabilir.

## Örnekler

1. İki boyutlu bir dizi oluşturma.

In [7]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array: \n", array)

Array: 
 [[1 2 3]
 [4 5 6]]


2. 3 satır ve 4 sütundan oluşan iki boyutlu bir dizi aşağıdaki gibi oluşturulur.

In [8]:
array1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: \n", array1)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3. Dizilerin kaç boyutlu olduğunu öğrenme.

In [9]:
print("array' s dimention:", array.ndim)
print("array1' s dimention:", array1.ndim)

array' s dimention: 2
array1' s dimention: 2


4. Dizilerin satır ve sütun sayısını öğrenme.

In [10]:
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: \n", array2)
print("Array' dimention: ", array2.ndim)
print("The number of rows and columns in the array: ", array2.shape)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array' dimention:  2
The number of rows and columns in the array:  (3, 4)


5. Otomatik sayı dzisi oluşturma:

In [11]:
array3 = np.arange(0, 31)
print("Array: ", array3)

Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


- Sabit aralıkla artan sayı dizisi oluşturma:

In [12]:
array3 = np.arange(0, 31, 3)
print("Array: ", array3)

Array:  [ 0  3  6  9 12 15 18 21 24 27 30]


6. Bir diziyi kopyalamak.

In [13]:
array4 = np.arange(0, 30, 3)
array5 = array4.copy()
print("array4 : ", array4)
print("array5 : ", array5)

array4 :  [ 0  3  6  9 12 15 18 21 24 27]
array5 :  [ 0  3  6  9 12 15 18 21 24 27]


7. Rastgele sayılardan oluşan tek boyutlu bir dizi oluşturma.

In [14]:
array6 = np.random.random((4))
print("array6 : ", array6)

array6 :  [0.23853681 0.50843965 0.27211452 0.28819672]


- Rastgele `tam` sayılardan oluşan tek boyutlu bir dizi oluştuma.

In [15]:
array7 = np.random.randint(20, size=4)
print("array7 : ", array7)

array7 :  [ 1 12 18  3]


- 2 satırlı, 4 sütunlu rastgele sayılardan oluşan iki boyutlu bir dizi oluşturma.

In [16]:
array8 = np.random.random((2, 4))
print("array8 : \n", array8)
print("array8' s dimention: ", array8.ndim)

array8 : 
 [[0.93349167 0.9843284  0.64531606 0.50296983]
 [0.67122137 0.86765668 0.5292676  0.65416697]]
array8' s dimention:  2


- 2 satırlı, 4 sütunlu rastgele `tam` sayılardan oluşan iki boyutlu bir dizi oluşturma.

In [17]:
array9 = np.random.randint(0, 20, size=(2, 4))
print("array9 : \n", array9)
print("array9' s dimention: ", array9.ndim)

array9 : 
 [[14 17 12  9]
 [12 10 11 19]]
array9' s dimention:  2


8. Dizinin ilk satırını alma.

In [18]:
array10 = np.arange(8)
array10 = array10.reshape(2, 4)
array11 = array10[0]

print("array10: \n", array10)
print("array11: ", array11)

array10: 
 [[0 1 2 3]
 [4 5 6 7]]
array11:  [0 1 2 3]


9. Dizinin ilk sütununu alma.

In [19]:
array12 = np.arange(8)
array12 = array12.reshape(4, 2)
print("array12: \n", array12)

array13 = array12[:, 0]
print("array13: ", array13)

array12: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
array13:  [0 2 4 6]


10. 5 satır ve 3 sütundan ve 0' lardan oluşan matris oluşturma.

In [20]:
array14 = np.zeros((5, 3))
print("array14: \n", array14)

array14: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


11. Üç boyutlu 1' lerden oluşan matris oluşturma.

In [21]:
array15 = np.ones((2, 3, 4))
print("array15: \n", array15)

array15: 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


- Elemanlarının hepsi 5 olan `2x4` matris olşturma.

In [22]:
array16 = np.ones((2, 4)) * 5
print("array16: \n", array16)

array16: 
 [[5. 5. 5. 5.]
 [5. 5. 5. 5.]]


- Elemanları aynı olan dizi oluşturmak için `full()` metodunu da kullanabiliriz. `2x3` dizinin boyutunu belirlerken, matrisin 8' lerden oluşmasını istedik.

In [23]:
array17 = np.full((2, 3), 8)
print("array17: \n", array17)

array17: 
 [[8 8 8]
 [8 8 8]]


12. Birim matris oluşturma.

In [24]:
array18 = np.eye(3)
print("array18: \n", array18)

array18: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


13. Matris birleştirme.

In [25]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
matrix1 = np.array([[9, 10, 11, 12], [13, 14, 15, 16]])
mergeMatrix = np.concatenate([matrix, matrix1])
print("mergeMatrix: \n", mergeMatrix)

mergeMatrix: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Matris birleştirmede eğer `axis` değeri kullanılırsa matrisler yan yana diziliş gösterir. Yukarıdaki kodumuzu şu şekilde yazalım ve çıktımızı görelim:

In [26]:
mergeMatrix1 = np.concatenate([matrix, matrix1], axis=1)
print("mergeMatrix1: \n", mergeMatrix1)

mergeMatrix1: 
 [[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [27]:
mergeMatrix2 = np.concatenate([matrix, matrix1], axis=0)
print("mergeMatrix2: \n", mergeMatrix2)

mergeMatrix2: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


14. Bir dizinin maksimum ve minimum değere sahip olan elemanlarını bulma.

In [28]:
array19 = np.random.randint(1, 20, size=(3, 4))
print("array19: \n", array19)
print("Maximim value of the array19: ", array19.max())
print("Minimum value of the array19: ", array19.min())

array19: 
 [[13 17 11  3]
 [14 14  7  8]
 [ 2 17  7 19]]
Maximim value of the array19:  19
Minimum value of the array19:  2


15. Bir dizideki tüm satırların ve sütunların ayrı ayrı toplamını bulma.

In [29]:
array20 = np.random.randint(0, 20, size=(3, 4))
print("array20: \n", array20)
print("Total of the rows of array20: ", array20.sum(axis=1))
print("Total of the columns of array20: ", array20.sum(axis=0))

array20: 
 [[ 8  6  3 14]
 [ 4 17 17 18]
 [ 1 18  1  2]]
Total of the rows of array20:  [31 56 22]
Total of the columns of array20:  [13 41 21 34]


16. Bir dizideki tüm elemanların ortalamasını bulma.

In [30]:
array21 = np.random.randint(0, 20, size=(3, 4))
print("array21: \n", array21)
print("The average of the elements of array21: ", array21.mean())

array21: 
 [[ 9  9 18  7]
 [ 3  6  9 10]
 [15  8 15 19]]
The average of the elements of array21:  10.666666666666666


17. Bir dizideki varyansı bulma.

In [31]:
array22 = np.random.randint(0, 20, size=(3, 4))
print("array22: \n", array22)
print("Variance of the array22: ", array22.var())

array22: 
 [[13 18 16  7]
 [ 7  8 10 16]
 [ 6 15 11  2]]
Variance of the array22:  22.1875


- Soru: Varyans nedir?

- Cevap: `Varyans` istatistiksel bir terimdir ve bir veri kümesindeki değerlerin ortalamadan ne kadar sapma gösterdiğini ölçer. Yani varyans, bir veri kümesindeki her bir verinin ortalamadan en karad uzaklaştığına bağlı olarak veri dağılımının ne kadar geniş olduğunu ölçer. `Varyans, bir veri kümesindeki her bir verinin ortalamadan ne kadar farklı olduğunu ölçmek için kullanılan kareli sapma değerlerinin toplamının n-1' e bölünmesi ile hesaplanır.` Burada `n`, veri kümesindeki toplam örneklemlerin sayısını temsil eder. Varyansın Kareköküne `Standart Sapma` denir ve varyansın ölçüm birimi ile aynı birimde ifade edilir. Daha düşük bir varyans değeri, örneklerin ortalamadan daha fazla uzaklaştığı anlamına gelir, daha yüksek bir varyans değeri, örneklerin ortalamadan daha fazla uzaklaştığı anlamına gelir.