# NumPy

NumPy, `Numerical Python` anlamaına gelir ve yüksek performanslı sayısal işlemler yapmak için kullanılan bir Python kütüphanesidir. NumPy temel özellikleri arasında çok boyutlu dizileri ve matrisler, matematiksel işlemler, rastgele sayı üretimi ve Fourier dönüşümleri yer almaktadır. Bu özellikler sayesinde Numpy, bilimsel ve mühendislik hesaplamaları için yaygın olarak kullanılan bir kütüphanedir.

NumPy kütüphanesi `np` kısaltma adıyla aşağıdaki gibi eklenir.

In [57]:
import numpy as np

print("Version of NumPy libary: ", np.__version__)

Version of NumPy libary:  2.3.2


Dizi oluşturma:

In [58]:
array = np.array([1, 2, 3, 4, 5, 6])
print("Array: ", array)

Array:  [1 2 3 4 5 6]


Dizinin veri tipini öğrenme: Yukarıdaki dizinin tipi `numpy` veri tiplerinden `ndarray` tipindedir. Python' da olduğu gibi `numpy` kütüphanesinin de kendine özgü veri tipleri vardır. `ndarray` bunlardan biridir.

In [59]:
print("Type of the array: ", type(array))

Type of the array:  <class 'numpy.ndarray'>


Dizi içindeki verilerin tipini öğrenme: Yukarıdaki dizinin içindeki veriler `int64` veri tipindedir.

In [60]:
print("Data type of array elements: ", array.dtype)

Data type of array elements:  int64


NumPy içindeki verilerin tipi en geniş anlamda tanımlanır: Örneğin dizinin içinde hem tam sayı hem de kayar noktalı sayı varsa bu durumda `dtype` değeri kayar noktalı sayı olarak belirlenir. Çünkü kayar noktalı sayı veri türü tam sayıları da kapsar. Kısacası NumPy dizileri, bellek verimliliği ve performans nedeniyle homojen veri tipleri gerektirir, bu nedenle bir dizi için sadece tek bir veri tipi tanımlanır.

In [61]:
array1 = np.array([1, 1.5, 2, 2.5, 3, 3.5, 4])
print("Data type of array elements: ", array1.dtype)

Data type of array elements:  float64


* Soru: Bir NumPy dizisi içinde string veri tipleri nasıl kullanılır?

* Cevap: Bir NumPy dizisi içinde stringler de olabilir. NumPy, dizi elemanları için farklı veri tipleri sağlar ve string veri tipleri de bunlardan biridir. NumPy dizilerinde string veri tipleri, `S` veya `U` karakterleriyle tanımlanır. `S` tipi veri tipleri, `byte` dizileri içindir. `S10` gibi bir veri tipi, her elemanın en fazla `10 byte` uzunluğunda bir `byte` dizisi olduğunu belirtir. Örneğin `hello` kelimesi `S5` tipinde bir dizi elemanıdır. `U` tipi veri tipleri, `Unicode` karakter dizileri içindir. `U10` gibi bir veri tipi, her elemanın en fazla 10 karakter uzunluğunda bir `Unicode` karakter dizisi olduğunu belirtir. Örneğin, `Merhaba` kelimesi `U7` tipinde bir dizi elemanıdır.

NumPy dizilerinde string veri tipleri, çeşitli uygulamalarda kullanılır. Örneğin metin verileri, dosya adları, etiketler ve sınıf adları gibi veriler string veri tipleri kullanılarak depolanabilir.

## Örnekler

1. İki boyutlu bir dizi oluşturma.

In [62]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array: \n", array)

Array: 
 [[1 2 3]
 [4 5 6]]


2. 3 satır ve 4 sütundan oluşan iki boyutlu bir dizi aşağıdaki gibi oluşturulur.

In [63]:
array1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: \n", array1)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3. Dizilerin kaç boyutlu olduğunu öğrenme.

In [64]:
print("array' s dimention:", array.ndim)
print("array1' s dimention:", array1.ndim)

array' s dimention: 2
array1' s dimention: 2


4. Dizilerin satır ve sütun sayısını öğrenme.

In [65]:
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: \n", array2)
print("Array' dimention: ", array2.ndim)
print("The number of rows and columns in the array: ", array2.shape)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array' dimention:  2
The number of rows and columns in the array:  (3, 4)


5. Otomatik sayı dzisi oluşturma:

In [66]:
array3 = np.arange(0, 31)
print("Array: ", array3)

Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


- Sabit aralıkla artan sayı dizisi oluşturma:

In [67]:
array3 = np.arange(0, 31, 3)
print("Array: ", array3)

Array:  [ 0  3  6  9 12 15 18 21 24 27 30]


6. Bir diziyi kopyalamak.

In [68]:
array4 = np.arange(0, 30, 3)
array5 = array4.copy()
print("array4 : ", array4)
print("array5 : ", array5)

array4 :  [ 0  3  6  9 12 15 18 21 24 27]
array5 :  [ 0  3  6  9 12 15 18 21 24 27]


7. Rastgele sayılardan oluşan tek boyutlu bir dizi oluşturma.

In [69]:
array6 = np.random.random((4))
print("array6 : ", array6)

array6 :  [0.23627662 0.69486391 0.13866205 0.91991945]


- Rastgele `tam` sayılardan oluşan tek boyutlu bir dizi oluştuma.

In [70]:
array7 = np.random.randint(20, size=4)
print("array7 : ", array7)

array7 :  [18  6 19  1]


- 2 satırlı, 4 sütunlu rastgele sayılardan oluşan iki boyutlu bir dizi oluşturma.

In [71]:
array8 = np.random.random((2, 4))
print("array8 : \n", array8)
print("array8' s dimention: ", array8.ndim)

array8 : 
 [[0.84739221 0.75766474 0.4371819  0.15434911]
 [0.26477216 0.63573185 0.62735619 0.206277  ]]
array8' s dimention:  2


- 2 satırlı, 4 sütunlu rastgele `tam` sayılardan oluşan iki boyutlu bir dizi oluşturma.

In [72]:
array9 = np.random.randint(0, 20, size=(2, 4))
print("array9 : \n", array9)
print("array9' s dimention: ", array9.ndim)

array9 : 
 [[13  2  4 13]
 [16  3 14  4]]
array9' s dimention:  2


8. Dizinin ilk satırını alma.

In [73]:
array10 = np.arange(8)
array10 = array10.reshape(2, 4)
array11 = array10[0]

print("array10: \n", array10)
print("array11: ", array11)

array10: 
 [[0 1 2 3]
 [4 5 6 7]]
array11:  [0 1 2 3]


9. Dizinin ilk sütununu alma.

In [74]:
array12 = np.arange(8)
array12 = array12.reshape(4, 2)
print("array12: \n", array12)

array13 = array12[:, 0]
print("array13: ", array13)

array12: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
array13:  [0 2 4 6]


10. 5 satır ve 3 sütundan ve 0' lardan oluşan matris oluşturma.

In [75]:
array14 = np.zeros((5, 3))
print("array14: \n", array14)

array14: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


11. Üç boyutlu 1' lerden oluşan matris oluşturma.

In [76]:
array15 = np.ones((2, 3, 4))
print("array15: \n", array15)

array15: 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


- Elemanlarının hepsi 5 olan `2x4` matris olşturma.

In [77]:
array16 = np.ones((2, 4)) * 5
print("array16: \n", array16)

array16: 
 [[5. 5. 5. 5.]
 [5. 5. 5. 5.]]


- Elemanları aynı olan dizi oluşturmak için `full()` metodunu da kullanabiliriz. `2x3` dizinin boyutunu belirlerken, matrisin 8' lerden oluşmasını istedik.

In [78]:
array17 = np.full((2, 3), 8)
print("array17: \n", array17)

array17: 
 [[8 8 8]
 [8 8 8]]


12. Birim matris oluşturma.

In [79]:
array18 = np.eye(3)
print("array18: \n", array18)

array18: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


13. Matris birleştirme.

In [80]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
matrix1 = np.array([[9, 10, 11, 12], [13, 14, 15, 16]])
mergeMatrix = np.concatenate([matrix, matrix1])
print("mergeMatrix: \n", mergeMatrix)

mergeMatrix: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Matris birleştirmede eğer `axis` değeri kullanılırsa matrisler yan yana diziliş gösterir. Yukarıdaki kodumuzu şu şekilde yazalım ve çıktımızı görelim:

In [81]:
mergeMatrix1 = np.concatenate([matrix, matrix1], axis=1)
print("mergeMatrix1: \n", mergeMatrix1)

mergeMatrix1: 
 [[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [82]:
mergeMatrix2 = np.concatenate([matrix, matrix1], axis=0)
print("mergeMatrix2: \n", mergeMatrix2)

mergeMatrix2: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


14. Bir dizinin maksimum ve minimum değere sahip olan elemanlarını bulma.

In [83]:
array19 = np.random.randint(1, 20, size=(3, 4))
print("array19: \n", array19)
print("Maximim value of the array19: ", array19.max())
print("Minimum value of the array19: ", array19.min())

array19: 
 [[ 7 15 18 19]
 [ 6  7 12 10]
 [ 4 18  9  4]]
Maximim value of the array19:  19
Minimum value of the array19:  4


15. Bir dizideki tüm satırların ve sütunların ayrı ayrı toplamını bulma.

In [84]:
array20 = np.random.randint(0, 20, size=(3, 4))
print("array20: \n", array20)
print("Total of the rows of array20: ", array20.sum(axis=1))
print("Total of the columns of array20: ", array20.sum(axis=0))

array20: 
 [[15 13  3 18]
 [ 3  0 11 16]
 [ 4  8 12 17]]
Total of the rows of array20:  [49 30 41]
Total of the columns of array20:  [22 21 26 51]


16. Bir dizideki tüm elemanların ortalamasını bulma.

In [85]:
array21 = np.random.randint(0, 20, size=(3, 4))
print("array21: \n", array21)
print("The average of the elements of array21: ", array21.mean())

array21: 
 [[ 9  9  2 10]
 [ 7  8  8  7]
 [ 6 19 15  6]]
The average of the elements of array21:  8.833333333333334


17. Bir dizideki varyansı bulma.

In [86]:
array22 = np.random.randint(0, 20, size=(3, 4))
print("array22: \n", array22)
print("Variance of the array22: ", array22.var())

array22: 
 [[ 0  5  6  1]
 [16 17 18  8]
 [ 0  5 11  0]]
Variance of the array22:  42.520833333333336


# Varyans (σ² veya s²)

## Popülasyon Varyansı
$$
\sigma^2 = \frac{\sum_{i=1}^{N} (x_i - \mu)^2}{N}
$$

## Örneklem Varyansı
$$
s^2 = \frac{\sum_{i=1}^{n} (x_i - \bar{x})^2}{n-1}
$$

### Değişkenler:
- $ x_i $: Her bir gözlem değeri
- $ N $: Popülasyondaki eleman sayısı
- $ n $: Örneklemdeki eleman sayısı
- $ \mu $: Popülasyon ortalaması
- $ \bar{x} $: Örneklem ortalaması


- Soru: Varyans nedir?

- Cevap: `Varyans` istatistiksel bir terimdir ve bir veri kümesindeki değerlerin ortalamadan ne kadar sapma gösterdiğini ölçer. Yani varyans, bir veri kümesindeki her bir verinin ortalamadan en karad uzaklaştığına bağlı olarak veri dağılımının ne kadar geniş olduğunu ölçer. `Varyans, bir veri kümesindeki her bir verinin ortalamadan ne kadar farklı olduğunu ölçmek için kullanılan kareli sapma değerlerinin toplamının n-1' e bölünmesi ile hesaplanır.` Burada `n`, veri kümesindeki toplam örneklemlerin sayısını temsil eder. Varyansın Kareköküne `Standart Sapma` denir ve varyansın ölçüm birimi ile aynı birimde ifade edilir. Daha düşük bir varyans değeri, örneklerin ortalamadan daha fazla uzaklaştığı anlamına gelir, daha yüksek bir varyans değeri, örneklerin ortalamadan daha fazla uzaklaştığı anlamına gelir.

18. Bir dizideki standart sapmayı bulma.

In [87]:
array23 = np.random.randint(0, 20, size=(3, 4))
print("array23: \n", array23)
print("Standard deviation of the array23: ", array23.std())

array23: 
 [[ 3  4  1 14]
 [ 6 11 18 17]
 [ 1  8 12 19]]
Standard deviation of the array23:  6.317963807008288


# Standart Sapma (σ veya s)

## Popülasyon Standart Sapması
$$
\sigma = \sqrt{\frac{\sum_{i=1}^{N} (x_i - \mu)^2}{N}}
$$

## Örneklem Standart Sapması
$$
s = \sqrt{\frac{\sum_{i=1}^{n} (x_i - \bar{x})^2}{n-1}}
$$

### Değişkenler:
- $ x_i $: Her bir gözlem değeri
- $ N $: Popülasyondaki eleman sayısı
- $ n $: Örneklemdeki eleman sayısı
- $ \mu $: Popülasyon ortalaması
- $ \bar{x} $: Örneklem ortalaması


- Soru: Standart sapma nedir?

- Cevap: Standart sapma, bir veri kümesindeki değerlerin ortalamadan ne kadar sapma gösterdiğiniz ölçen bir istatistik terimdir. Standart sapma, veri kümesindeki her bir örneğin ortalamadan ne kadar farklı olduğunu hesaplamak için kullanılır. `Standart sapma, veri kümesindeki örneklemlerin her birinin ortalamadan farkının karelerinin toplamının, örneklemlerin sayısının bir eksiğiyle bölümünden elde edilen değerin karekökü alınarak hesaplanır.` Bu hesaplamayla, standart sapma, veri kümesindeki örneklerin ne kadar yayıldığını, ne kadar değişken olduğunu ölçer. Standart sapma, varyansın kare kökü olarak hesaplanabilir. Standart sapma, varyans gibi veri kümesinin ölçüm birimi ile aynı birimden ifade edilir. Bir veri kümesindeki standart sapma daha yüksekse, veri kümesindeki örneklerin ortalamadan daha fazla sapma gösterdiği anlamına gelir ve veri kümesinin daha değişken olduğunu ifade eder. Standart sapma daha düşükse, veri kümesindeki örneklerin ortalamaya daha yakın olduğu ve veri kümesinin daha homojen olduğu anlamına gelir.

`Ek bilgi:` Diziler arasında matematiksel gerçekleşebilir ancak dizilerin boyutu ve şekli birbiri ile uyumlu olmalıdır. Yani aynı satır ve sütun sayılarına sahip olmalıdır.

`Farklı dizileri toplama:` İki farklı dizimiz olsun. Bu dizilerdeki karşılıklı satır ve sütunları toplayalım. Aşağıdaki örnekte `array24`' deki 1 değeri, `array25`' taki 7 değerini dek geleceği için bu ikisi toplanır ve 8 değerine ulaşılır. Diğer değerler de aynı şekilde toplanır.

In [88]:
array24 = np.array([[1, 2, 3], [4, 5, 6]])
array25 = np.array([[7, 8, 9], [10, 11, 12]])

result = array24 + array25
print("result: \n", result)

result: 
 [[ 8 10 12]
 [14 16 18]]


`Farklı dizileri çıkarma:` Farklı bir örnekle `array26` değerlerini `array27` değerlerinden çikaralım.

In [89]:
array26 = np.array([[12, 45, 32], [10, 32, 56]])
array27 = np.array([[3, 2, 4], [7, 7, 9]])

result = array26 - array27
print("result: \n", result)

result: 
 [[ 9 43 28]
 [ 3 25 47]]


`Farklı dizileri çarpma:` Farklı bir örnekle `array28` değerlerini `array29`  değerleri ile çarpalım.

In [90]:
array28 = np.array([[3, 2, 4], [3, 8, 5]])
array29 = np.array([[9, 4, 7], [1, 2, 6]])

result = array28 * array29
print("result: \n", result)

result: 
 [[27  8 28]
 [ 3 16 30]]


`Farklı dizileri bölme:` Farklı bir örnekle `array30` değerlerini `array31` değerlerine bölelim. Sonuçların `float` olarak çıktığına dikkat edin.

In [91]:
array30 = np.array([[9, 4, 8], [6, 16, 35]])
array31 = np.array([[3, 2, 4], [3, 8, 5]])

result = array30 / array31
print("result: \n", result)

result: 
 [[3. 2. 2.]
 [2. 2. 7.]]


`Farklı diziler arası modül işlemi:` Modül işlemi bilindiği üzere bölümlerden kalan sayıyı verir. Bunun aşağıdaki dizi değerleri arasında gösterelim.

In [92]:
array32 = np.array([[12, 45, 32], [10, 32, 56]])
array33 = np.array([[3, 2, 4], [7, 7, 9]])

result = array32 % array33
print("result: \n", result)

result: 
 [[0 1 0]
 [3 4 2]]


`Bir dizi ile sayının toplanması:` Aşağıdaki işleme `array34`' ün her değerine `10` değeri eklenir.

In [93]:
array34 = np.array([[1, 2, 3], [4, 5, 6]])

result = array34 + 10
print("result: \n", result)

result: 
 [[11 12 13]
 [14 15 16]]


`Ek bilgi:` Bir dizi ile bir sayı nasıl toparlanabiliyorsa diğer tüm işlemler de yapılabilir.

`Dizilerde trigonometrik işlemler:` Dizilerde trigonometrik işlemler de yapılabilir. Aşağıdaki örnekte sinüs alma işlemi gösterilmiştir.

In [94]:
array35 = np.array([[1, 2, 3], [4, 5, 6]])

result = np.sin(array35)
print("result: \n", result)

result: 
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


`Dizilerde karekök ve diğer işlemler:` Yukarıda gösterilen trigonometrik işlem haricinde karekök gibi işlemlerde yapılabilir. Bunun için yapmamız gereken sadece `sin()` metodu yerine `sqrt()` metodunu kullanmaktır. Bunların haricinde `exp()` e sayısı (e≈2.718281828459045…), `log()` logaritma gibi işlemler de aynı yöntemle yapılır.

`Matris çarpma:` İki matrisin çarpımı `dot()` metodu veya `@` kullanılarak hesaplanır. Ancak matrislerin boyutlarına dkkat etmek önemlidir. İlk matrisin sütun sayısı ikinci matrisin satır sayısına eşit olmalıdır.

## Matris Çarpma Koşulu

Eğer
$$
A_{m \times n} \quad \text{ve} \quad B_{n \times p}
$$
matrisleri verilmişse,

$$
C = A \times B
$$
çarpımı tanımlıdır ve sonuç
$$
C_{m \times p}
$$
boyutunda bir matris olur.

---

### Örnek:

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}_{2 \times 3}
\quad
B =
\begin{bmatrix}
7 & 8 \\
9 & 10 \\
11 & 12
\end{bmatrix}_{3 \times 2}
$$


✅ Burada $ A $ matrisinin sütun sayısı (3), $ B $ matrisinin satır sayısına (3) eşittir.

Sonuç $ C_{2 \times 2} $ boyutunda bir matristir.

In [95]:
array36 = np.array([[1, 2, 3], [4, 5, 6]])
array37 = np.array([[7, 8], [9, 10], [11, 12]])

result = np.dot(array36, array37)
result1 = array36 @ array37

print("result: \n", result)
print("result1: \n", result1)

result: 
 [[ 58  64]
 [139 154]]
result1: 
 [[ 58  64]
 [139 154]]


`Transpozisyon işlemi:` Transpozisyon işlemi, bir dizi ya da matris sütun ve satırlarının yarlerini değiştirir.  Yani bir matrisin transpozu, orjinal matrisin sütunlarının satırlarla ve satırların da sütulanlarla yer değiştiröiş halidir.

NumPy' de transpozisyon işlemi, `transpose()` fonksiyonu ile yapılır. Bu fonksiyon, bir dizinin boyutlarını tersine çevirir.

Örneğin, bir 2D dizi (matris) için, `transpose()` işlemi, sütunları satırlara ve satırları da sütunlara çevirir.

In [96]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
transposeMatrix = matrix.transpose()
print("Matrix: \n", matrix)
print("Matrix's shape: \n", matrix.shape)
print("transposeMatrix: \n", transposeMatrix)
print("transposeMatrix' shape: \n", transposeMatrix.shape)

Matrix: 
 [[1 2]
 [3 4]
 [5 6]]
Matrix's shape: 
 (3, 2)
transposeMatrix: 
 [[1 3 5]
 [2 4 6]]
transposeMatrix' shape: 
 (2, 3)


`Ek bilgi:` `transpose()` metodu yerine, `T` komutu da kullanılabilir.

In [97]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print("Matrix: \n", matrix)
print("Matrix's shape: \n", matrix.shape)
print("transposeMatrix: \n",  matrix.T)
print("transposeMatrix' shape: \n", matrix.T.shape)

Matrix: 
 [[1 2]
 [3 4]
 [5 6]]
Matrix's shape: 
 (3, 2)
transposeMatrix: 
 [[1 3 5]
 [2 4 6]]
transposeMatrix' shape: 
 (2, 3)


`Dizi ve matrislerde boolean işlemleri:` Koşullu işlemler yapıp dizimizdeki değerlerin doğruluğunu kontrol edip 'True' veya `False` çıktıları alabiliriz.

In [98]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
controle = matrix < 4
print("matrix: \n", matrix)
print("Controle: \n", controle)

matrix: 
 [[1 2]
 [3 4]
 [5 6]]
Controle: 
 [[ True  True]
 [ True False]
 [False False]]


`Ek bilgi:` Sadece koşulu sağlayan değerleri dizi haline getirebiliriz. Yukarıdaki örneği tekrar baz alırsak;

In [99]:
valuesOfControle = matrix[matrix < 4]
print("Values of controle: \n", valuesOfControle)

Values of controle: 
 [1 2 3]


`.npy Dosya Formatı:` NumPy dizileri diskte depolamak ve okumak için kullanılabilen bir dosya formatı olan `.npy` dosyalarını destekler. `.npy` dosyaları, NumPy tarafından sağlanan `save()` ve `load()` fonksiyonlarını kullanarak oluşturulur ve okunur. Bu dosyalar, yüksek performanslı  veri depolama ve aktarımı sağlar.

`Ek bilgi:` NumPy ayrıca `.npz` uzantılı sıkıştırılmış dosyaları da destekler. Bu dosyalar, birden fazla `.npy` dosyasını içerebilir ve sıkıştırılmış bir arşiv olarak saklanabilir. Bu dosyaları oluşturmak ve okumak için de NumPy tarafından sağlanan `savez()` ve `loadz()` fonksiyonları kullanılabilir.

In [100]:
matrix = np.array([1, 2, 3, 4, 5])
np.save("try.npy", matrix)
newMatrix = np.load("try.npy")
print("matrix: \n", matrix)
print("newMatrix: \n", newMatrix)

matrix: 
 [1 2 3 4 5]
newMatrix: 
 [1 2 3 4 5]


`Bir .csv uzantılı dosyanın içindeki verileri çekme:` Numpy, `.csv` dosyalarını okumak için `genformtxt()` fonksiyonunu kullanabilirrsiniz.  Bu fonksiyon, bir `.csv` dosyasını NumPy dizisi olarak okur.

In [101]:
path = "example.csv"
data = np.genfromtxt(path, delimiter=",")
print("data: \n", data)

data: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


`Ek bilgi:` `delmiter` parametresi, dosyanın nasıl ayrıldığını belirtir. Burada `,` karakteri kullanıldı.